FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    git \
    curl \
    ffmpeg \
    espeak-ng \
    make \
    g++ \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    torch transformers kernels \
    torchaudio soundfile numpy \
    kokoro misaki pyopenjtalk \
    fugashi unidic-lite jaconv \
    mojimoji accelerate torchvision \
    "fastapi[standard]"

# WORKDIR /app/python

CMD ["sleep", "infinity"]
# CMD ["python", "main.py"]